print(" WINBOND IT SOLUTIONS")
print("TEL:0758075999")
print("Date of issue...................")
print("Laptop model/details:....................")
print("SERIAL No...........")
print("COMMENT..........")
print("AMOUNT.................")
print("Technician...........")
print("Client Signature...........Admin Signature............")

